docker_image: &docker_image
  docker:
    - image: openjdk:11-slim

set_working_directory: &set_working_directory
  working_directory: ~/simple-yaml

restore_cache_keys: &restore_cache_keys
  keys:
    - v1-dependencies-{{ checksum "build.gradle" }}
    - v1-dependencies-

save_cache_config: &save_cache_config
  paths:
    - ~/.gradle
  key: v1-dependencies-{{ checksum "build.gradle" }}

version: 2.1
jobs:
  test:
    <<: *docker_image
    <<: *set_working_directory
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_keys
      - run: |
          ./gradlew build
  build:
    <<: *docker_image
    <<: *set_working_directory
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_keys
      - run: ./gradlew build artifactoryPublish -Dsnapshot=true
      - save_cache:
          <<: *save_cache_config
      - store_artifacts:
          path: build/libs
  publish:
    <<: *docker_image
    <<: *set_working_directory
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache_keys
      - run: ./gradlew build bintrayUpload -x test
      - save_cache:
          <<: *save_cache_config

workflows:
  build_test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
      - build:
          filters:
            branches:
              only: master
  publish_artifacts:
    jobs:
      - publish:
          filters:
            branches:
              only: non-existent-branch
            tags:
              only: /^v[0-9\.]+$/
